// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opwiwaysvdmkajmhhbzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wd2l3YXlzdmRta2FqbWhoYnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzAyODQsImV4cCI6MjA2NTY0NjI4NH0.U-eyRsfuwHtKq94BD-sYiDVjH2yg9b2fp33xeSPlmL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);